# Generated by Django 5.0.1 on 2024-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POGaurd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poNumber', models.PositiveIntegerField(unique=True)),
                ('sent_to_vendor', models.BooleanField(default=False)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('sent_datetime', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('waiting_time_for_confirmation', models.PositiveSmallIntegerField(default=3)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
