# Generated by Django 5.0.1 on 2024-02-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pogaurd',
            name='hasNotified',
            field=models.BooleanField(default=False),
        ),
    ]
