# Generated by Django 5.0.1 on 2024-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poController', '0002_pogaurd_hasnotified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pogaurd',
            name='sent_to_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
