# Generated by Django 5.0.1 on 2024-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poController', '0003_alter_pogaurd_sent_to_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pogaurd',
            name='waiting_time_for_confirmation',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
