# Generated by Django 5.0.1 on 2024-02-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poController', '0004_alter_pogaurd_waiting_time_for_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pogaurd',
            name='errorMsg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pogaurd',
            name='hasError',
            field=models.BooleanField(default=False),
        ),
    ]
