version: "3.4"

services:
  backend:
    image: pogaurd-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - ./backend/.env
    ports:
      - "6500:6500"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env.DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: pogaurd-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "2222:22"
    depends_on:
      - backend

volumes:
  static:
  media:
  postgres_data:
